-- SUPABASE USER NOTIFICATIONS & BROADCASTS SETUP
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

CREATE TABLE IF NOT EXISTS public.user_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL DEFAULT 'all',
  message text NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS with open read/write policies for platform announcements
ALTER TABLE public.user_notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read on user_notifications" ON public.user_notifications;
CREATE POLICY "Allow public read on user_notifications" 
  ON public.user_notifications FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on user_notifications" ON public.user_notifications;
CREATE POLICY "Allow public insert on user_notifications" 
  ON public.user_notifications FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on user_notifications" ON public.user_notifications;
CREATE POLICY "Allow public update on user_notifications" 
  ON public.user_notifications FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete on user_notifications" ON public.user_notifications;
CREATE POLICY "Allow public delete on user_notifications" 
  ON public.user_notifications FOR DELETE USING (true);
